In [2]:
import numpy as np

In [2]:
# Creating numpy array using python lists
my_list  = [1 , 2, 3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
a = np.array(my_matrix)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Creating arrays using Built IN methods
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
#numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)
#Array of zeroes with the same shape and type as a
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
#numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)
#Array of ones with the same shape and type as a
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
np.zeros_like((3, 3))

array([0, 0])

In [19]:
np.ones_like((3, 3))

array([1, 1])

In [23]:
#Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.eye((3,4))

TypeError: 'tuple' object cannot be interpreted as an integer

In [27]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [28]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [30]:
#Arranging the numbers
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
np.arange(10, 21, 2)

array([10, 12, 14, 16, 18, 20])

In [35]:
np.arange(10, 20, 10)

array([10])

In [37]:
#LinSpace - Evenly dividing the range as pe rthe given number
np.linspace(start=10, stop=20, num=10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [42]:
np.linspace(start=10, stop=20, num=11, dtype=float, endpoint = False)

array([10.        , 10.90909091, 11.81818182, 12.72727273, 13.63636364,
       14.54545455, 15.45454545, 16.36363636, 17.27272727, 18.18181818,
       19.09090909])

In [43]:
# 3. Rand - Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
# [1,5]=1,2,3,4,5
#[1,5)=1,2,3,4
np.random.rand(3)

array([0.93707913, 0.6109589 , 0.76080546])

In [45]:
np.random.rand(3, 3)

array([[0.08551138, 0.53404107, 0.0851814 ],
       [0.84052177, 0.09502878, 0.03102409],
       [0.16474088, 0.34974145, 0.74587267]])

In [48]:
# randn - returns the samples in 'Standard normal distribution'
np.random.randn(3)

array([-1.13893128,  0.26348422,  1.34289265])

In [53]:
np.random.randn(3, 3)

array([[-0.03927911,  0.212944  ,  1.01288176],
       [ 0.8909502 ,  0.49716833,  1.14599606],
       [-0.09908363,  0.94957257, -0.45624643]])

In [57]:
# randint - returs a radom integer from low-inclusive and high-exclusive
np.random.randint(10)

5

In [62]:
np.random.randint(10, 20)

11

In [63]:
np.random.randint(10, 20, 5)

array([12, 17, 11, 12, 16])

In [64]:
np.random.random_integers(10)

<ipython-input-64-bd77ee63ccfa>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  np.random.random_integers(10)


3

In [68]:
#Mathematics and Statistics
a = np.random.randn(3,3)
a

array([[-0.61314961,  1.0683833 , -1.7755746 ],
       [ 0.75125193, -0.12784651,  1.00667025],
       [-0.33472253, -0.2906128 ,  1.34081415]])

In [69]:
a.mean() # calculate the mean of flattned array

0.11391262060903751

In [70]:
np.mean(a)

0.11391262060903751

In [71]:
b = np.array(my_matrix)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
#axis zero means calculations to be done column wise
b.mean(axis = 0)

array([4., 5., 6.])

In [73]:
#axis one means calculations to be done row wise
b.mean(axis = 1)

array([2., 5., 8.])

In [74]:
b.sum(0)

array([12, 15, 18])

In [75]:
b.sum(1)

array([ 6, 15, 24])

In [76]:
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [77]:
c.shape

(3,)

In [79]:
c = np.array([1, 2, 3], ndmin = 2)
c

array([[1, 2, 3]])

In [80]:
c.shape

(1, 3)

In [86]:
d = np.arange(27).reshape(3, 3, 3)
d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
e = np.ones(18).reshape(3, 3, 2)
e

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [94]:
f = np.ones(18).reshape(3, 3, -1)
f

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [96]:
f = np.ones(18).reshape(-1, 3, 3)
f

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [97]:
f.ndim

3

In [98]:
f.dtype

dtype('float64')

In [99]:
arr = f.astype(np.int64)
arr

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int64)

In [100]:
arr.dtype

dtype('int64')

In [101]:
type(arr)

numpy.ndarray

In [103]:
arr1 = np.array([1 ,2, 3, 4, 5, 6])
arr1.shape

(6,)

In [110]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [111]:
x = np.arange(5)
y = np.arange(5, 10)
x, y

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [112]:
cond = np.array([True, True, False, False, True])
cond

array([ True,  True, False, False,  True])

In [114]:
result = np.where(cond, x, y)
result

array([0, 1, 7, 8, 4])

In [123]:
arr = np.random.rand(10)
arr

array([0.69801519, 0.23115828, 0.64543868, 0.80477983, 0.61042969,
       0.54895971, 0.93812375, 0.14190537, 0.9598036 , 0.50634295])

In [125]:
arr1 = np.where(arr>0.5, True, False)
arr1

array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True])

In [4]:
cond1 = [True, True, False, False]
cond2 = [True, False, True, False]
result = []

for i in range(len(cond1)):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

result


[0, 1, 2, 3]

In [5]:
np.where(cond1 and cond2, 0,
        np.where(cond1, 1,
                np.where(cond2, 2, 3)))

array([0, 1, 0, 3])

In [7]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr3 * arr3

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
arr3 / arr3

<ipython-input-9-834f654fc358>:1: RuntimeWarning: invalid value encountered in true_divide
  arr3 / arr3


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
1 / arr3

<ipython-input-10-d4075aef02cc>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr3


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
arr3**4

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561],
      dtype=int32)

In [12]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr4[5]

5

In [14]:
arr4[8]

8

In [15]:
arr4[:5]

array([0, 1, 2, 3, 4])

In [16]:
arr4[5:9]

array([5, 6, 7, 8])

In [17]:
arr4[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr4[3:10:3] = 50

In [21]:
arr4

array([ 0,  1,  2, 50,  4,  5, 50,  7,  8, 50])

In [23]:
arr5 = arr4[2:5]

In [24]:
arr5[:] = 25

In [25]:
arr4

array([ 0,  1, 25, 25, 25,  5, 50,  7,  8, 50])

In [27]:
arr2d = np.arange(9).reshape(3,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr2d[0]

array([0, 1, 2])

In [29]:
arr2d[0][3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [30]:
arr2d[0][2]

2

In [32]:
arr2d[0,2]

2

In [33]:
arr3d = np.arange(27).reshape(2, 3, 4)

ValueError: cannot reshape array of size 27 into shape (2,3,4)

In [34]:
arr3d = np.random.randn(2, 3, 4)

In [35]:
arr3d

array([[[ 0.45388446, -0.9110434 ,  1.38019258,  1.45198724],
        [-0.97727279,  2.60858402,  1.58957897,  0.60794878],
        [ 0.78482456, -1.03040702,  0.73544394,  1.23861612]],

       [[ 0.74940205,  0.74072767, -0.31597508,  1.01843374],
        [ 0.93606817,  0.45409832,  0.03124296, -1.18599655],
        [-0.5236116 ,  1.26239548, -0.1709202 ,  0.32200097]]])

In [36]:
arr3d[0]

array([[ 0.45388446, -0.9110434 ,  1.38019258,  1.45198724],
       [-0.97727279,  2.60858402,  1.58957897,  0.60794878],
       [ 0.78482456, -1.03040702,  0.73544394,  1.23861612]])

In [37]:
arr3d[0][1][2]

1.5895789654373034

In [38]:
arr3d[0, 1, 2]

1.5895789654373034

In [39]:
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
arr2d[0:2] # First part tells me about which rows to operate on

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr2d[0:2]

In [1]:
#Boolean Indexing
import numpy as np
bool_arr = np.array([True, False, True, False, True, False, True, False, True, False])
arr = np.arange(10)


In [2]:
arr[bool_arr]

array([0, 2, 4, 6, 8])

In [8]:
arr = np.random.randn(2,3)

In [9]:
arr

array([[ 0.39940702, -0.31420722,  0.60368866],
       [ 0.23029917,  0.6128096 ,  0.40147423]])

In [12]:
arr[arr < 0] = 1
arr

array([[0.39940702, 1.        , 0.60368866],
       [0.23029917, 0.6128096 , 0.40147423]])

In [10]:
arr < 0

array([[False,  True, False],
       [False, False, False]])

In [13]:
#Demean Data
arr = np.random.randn(5, 4)
arr

array([[-2.05373899,  0.31626443, -0.97229182, -0.2031233 ],
       [-0.54427345,  0.48464944,  2.25142552,  1.6733937 ],
       [ 0.087759  ,  0.33159746, -1.76678736, -0.58173984],
       [-2.34110847, -1.24653729,  1.07435289,  0.33854301],
       [ 0.51972144, -1.12042622, -1.55044766, -0.88738493]])

In [18]:
arr.mean(0).reshape(1, 4)

array([[-0.86632809, -0.24689044, -0.19274969,  0.06793773]])

In [16]:
demean = arr - arr.mean(0)
demean

array([[-1.18741089,  0.56315486, -0.77954213, -0.27106103],
       [ 0.32205464,  0.73153988,  2.44417521,  1.60545597],
       [ 0.9540871 ,  0.5784879 , -1.57403767, -0.64967757],
       [-1.47478038, -0.99964686,  1.26710257,  0.27060528],
       [ 1.38604953, -0.87353579, -1.35769797, -0.95532266]])

In [17]:
demean.mean(0)

array([0.0000000e+00, 0.0000000e+00, 4.4408921e-17, 0.0000000e+00])

In [19]:
arr.mean(1).reshape(5,1)

array([[-0.72822242],
       [ 0.9662988 ],
       [-0.48229268],
       [-0.54368747],
       [-0.75963434]])

In [20]:
demean = arr - arr.mean(1).reshape(5,1)
demean

array([[-1.32551657,  1.04448685, -0.2440694 ,  0.52509912],
       [-1.51057225, -0.48164936,  1.28512672,  0.7070949 ],
       [ 0.57005169,  0.81389015, -1.28449467, -0.09944716],
       [-1.79742101, -0.70284983,  1.61804035,  0.88223048],
       [ 1.27935578, -0.36079188, -0.79081332, -0.12775059]])

In [2]:
import numpy as np
arr4d = np.random.randn(3, 4, 5, 2)
arr4d

array([[[[-1.33344161e+00, -1.00920848e+00],
         [ 8.87936044e-01,  3.96685138e-01],
         [ 3.66591344e-02,  6.31454064e-01],
         [ 1.51745679e-01, -2.38649341e-01],
         [-2.89641527e-01, -2.57616052e-01]],

        [[-6.17413297e-01, -3.28120518e-01],
         [ 2.47372643e+00,  2.25486488e+00],
         [-7.36060534e-01,  5.00470864e-02],
         [ 1.24307673e+00, -1.08343091e+00],
         [ 6.52082351e-01,  1.21157417e+00]],

        [[ 1.10982883e+00, -5.63599043e-01],
         [ 2.17567939e+00,  2.53721651e-01],
         [-4.11556565e-01,  8.98345684e-01],
         [ 5.66086437e-01, -3.09143835e-01],
         [-9.52040513e-01,  2.03880452e+00]],

        [[-9.17883719e-01,  1.03676560e-01],
         [-9.26732415e-01,  6.69389834e-02],
         [-1.72450427e+00, -1.58049359e+00],
         [-1.37778837e+00,  1.94705368e-01],
         [ 4.53643371e-03,  1.13454868e+00]]],


       [[[ 2.82476901e-01, -2.27093536e+00],
         [ 2.10845468e+00, -4.46034233e-01],


In [23]:
arr4d.mean(0).shape

(4, 5, 2)

In [25]:
arr4d.mean(1).shape

(3, 5, 2)

In [26]:
arr4d.mean(2).shape

(3, 4, 2)

In [29]:
arr4d.mean(3).shape

(3, 4, 5)

In [30]:
arr4d.mean(4).shape

IndexError: tuple index out of range

In [31]:
#Demeaning 3D Array


In [32]:
np.sqrt(arr)

<ipython-input-32-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[       nan, 0.56237392,        nan,        nan],
       [       nan, 0.69616768, 1.5004751 , 1.2935972 ],
       [0.29624146, 0.575845  ,        nan,        nan],
       [       nan,        nan, 1.03650995, 0.58184449],
       [0.72091708,        nan,        nan,        nan]])

In [33]:
np.square(arr)

array([[4.21784382, 0.10002319, 0.94535138, 0.04125908],
       [0.29623359, 0.23488508, 5.06891688, 2.80024649],
       [0.00770164, 0.10995688, 3.12153757, 0.33842124],
       [5.48078888, 1.55385522, 1.15423412, 0.11461137],
       [0.27011038, 1.25535492, 2.40388794, 0.78745201]])

In [34]:
np.sin(arr)

array([[-0.88563223,  0.31101843, -0.82617911, -0.2017294 ],
       [-0.51779666,  0.4658982 ,  0.77717693,  0.9947415 ],
       [ 0.0876464 ,  0.32555388, -0.98085516, -0.54947842],
       [-0.71769334, -0.94788706,  0.87928211,  0.33211316],
       [ 0.49663838, -0.90028606, -0.99979297, -0.77542313]])

In [35]:
np.cos(arr)

array([[-0.4643873 ,  0.95040388,  0.56340756,  0.97944129],
       [ 0.85550372,  0.88483833, -0.62928215, -0.10241748],
       [ 0.99615165,  0.94552349, -0.19473869,  0.83550791],
       [-0.6963593 ,  0.31860652,  0.47630134,  0.94323955],
       [ 0.86795756,  0.43529876,  0.02034726,  0.63144197]])

In [36]:
np.log(arr)

<ipython-input-36-a67b4ae04e95>:1: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([[        nan, -1.15117662,         nan,         nan],
       [        nan, -0.72432946,  0.81156358,  0.51485372],
       [-2.43316083, -1.10383351,         nan,         nan],
       [        nan,         nan,  0.07171851, -1.08310413],
       [-0.6544623 ,         nan,         nan,         nan]])

In [37]:
x = np.arange(10)
y = np.arange(10, 20)

In [38]:
x - y

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [39]:
np.subtract(x,y)

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [40]:
np.add(x, y)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [3]:
arr = np.random.randn(10, 5)
np.save("fille_arr", arr)

In [43]:
np.load("fille_arr.npy")

array([[ 6.80961866e-01, -4.16291631e-01, -4.77490277e-01,
        -8.86197476e-01,  3.42164347e-04],
       [-3.11601377e-01, -1.31880988e+00,  1.36741419e+00,
        -5.27585951e-01, -3.04343203e-01],
       [-6.48759748e-01, -3.54729518e-01, -1.54111533e+00,
        -6.99608355e-01, -5.06633769e-01],
       [ 3.24372562e-01, -5.20119424e-01, -1.04732141e+00,
        -9.39069143e-01,  1.21853908e-01],
       [ 1.23218845e+00,  5.52675237e-02, -2.35740231e-01,
         1.76074607e+00,  9.05984245e-01],
       [ 1.47338177e+00, -7.40548617e-02,  5.13734891e-01,
        -6.03988401e-01,  3.28252739e+00],
       [ 7.54046440e-01, -6.45354103e-01, -6.80515023e-01,
         2.16341487e-01,  8.29923434e-01],
       [-3.98135318e-01,  9.04198648e-01, -8.82706680e-01,
         2.15064554e+00,  1.12916005e+00],
       [ 3.02409264e-01,  2.94063426e-01,  4.26713867e-01,
         3.87460614e-01, -1.97481506e-01],
       [ 8.78499020e-01, -3.73401318e-01, -3.50057120e-01,
         4.17959705e-01

In [48]:
np.savez('file_zip.npz', a = arr, b = arr)

In [52]:
arrs = np.load('file_zip.npz')
arrs['a']

array([[ 6.80961866e-01, -4.16291631e-01, -4.77490277e-01,
        -8.86197476e-01,  3.42164347e-04],
       [-3.11601377e-01, -1.31880988e+00,  1.36741419e+00,
        -5.27585951e-01, -3.04343203e-01],
       [-6.48759748e-01, -3.54729518e-01, -1.54111533e+00,
        -6.99608355e-01, -5.06633769e-01],
       [ 3.24372562e-01, -5.20119424e-01, -1.04732141e+00,
        -9.39069143e-01,  1.21853908e-01],
       [ 1.23218845e+00,  5.52675237e-02, -2.35740231e-01,
         1.76074607e+00,  9.05984245e-01],
       [ 1.47338177e+00, -7.40548617e-02,  5.13734891e-01,
        -6.03988401e-01,  3.28252739e+00],
       [ 7.54046440e-01, -6.45354103e-01, -6.80515023e-01,
         2.16341487e-01,  8.29923434e-01],
       [-3.98135318e-01,  9.04198648e-01, -8.82706680e-01,
         2.15064554e+00,  1.12916005e+00],
       [ 3.02409264e-01,  2.94063426e-01,  4.26713867e-01,
         3.87460614e-01, -1.97481506e-01],
       [ 8.78499020e-01, -3.73401318e-01, -3.50057120e-01,
         4.17959705e-01

In [4]:
np.savetxt('arr.txt', arr, delimiter=',')

In [7]:
np.loadtxt('arr.txt', delimiter=',')

array([[-1.07455738e+00,  4.66020139e-01, -4.23265698e-01,
        -6.58990488e-01, -6.47334166e-01],
       [-3.49243966e-01,  1.08797329e-03, -6.04512229e-01,
         1.10207893e+00,  1.18120999e+00],
       [ 4.22651612e-01, -8.71465982e-01,  1.57217218e+00,
         1.50874972e+00, -1.07186263e+00],
       [-7.13900357e-02,  2.70291834e-01,  1.61480261e-01,
         2.23019639e-01, -1.00156610e+00],
       [-6.06497915e-01, -1.14045596e+00, -1.83338416e+00,
         1.49787149e+00, -6.01677665e-01],
       [ 1.41064909e+00, -9.14515391e-01,  8.30884092e-01,
         1.90836617e-01, -2.83140011e-02],
       [-1.42889633e+00, -1.36366708e+00, -1.12338614e+00,
        -1.92322068e-01,  3.67786310e-01],
       [ 1.42762498e+00,  1.78937093e+00, -1.36396299e+00,
        -1.58330389e-01,  1.04111632e-01],
       [ 9.00482602e-01, -1.65433541e-01, -4.22974979e-01,
        -1.17979606e+00, -6.15883443e-01],
       [ 9.29974373e-01, -4.04015041e-01, -4.53691895e-01,
        -7.93680674e-01

In [14]:
arr3d = np.arange(18).reshape(2,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [17]:
arr3d.mean(0)

array([[ 4.5,  5.5,  6.5],
       [ 7.5,  8.5,  9.5],
       [10.5, 11.5, 12.5]])

In [18]:
arr3d.mean(0).shape

(3, 3)

In [19]:
demean = arr3d - arr3d.mean(0)
demean

array([[[-4.5, -4.5, -4.5],
        [-4.5, -4.5, -4.5],
        [-4.5, -4.5, -4.5]],

       [[ 4.5,  4.5,  4.5],
        [ 4.5,  4.5,  4.5],
        [ 4.5,  4.5,  4.5]]])

In [24]:
arr3d.mean(1)

array([[ 3.,  4.,  5.],
       [12., 13., 14.]])

In [25]:
demean = arr3d - arr3d.mean(1).reshape(2, 3, 1)
demean

array([[[-3., -2., -1.],
        [-1.,  0.,  1.],
        [ 1.,  2.,  3.]],

       [[-3., -2., -1.],
        [-1.,  0.,  1.],
        [ 1.,  2.,  3.]]])